apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: bookmanagement
  labels:
    app: order-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: order-api
        image: bookmanagement/order-api:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ASPNETCORE_URLS
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ConnectionStrings__DefaultConnection
          value: "Server=sqlserver;Database=OrderDb;User=sa;Password=$(SA_PASSWORD);TrustServerCertificate=True;"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: sa-password
        - name: RabbitMQ
          value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@rabbitmq:5672/"
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: rabbitmq-user
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: rabbitmq-password
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: order-api
  namespace: bookmanagement
  labels:
    app: order-api
spec:
  selector:
    app: order-api
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP 